export type mode_t        = "Pokepos" | "Cnc";
export type menus_t       = "Service" | "Journal" | "Reprint" | "Settings" | "Menu" | "Hello" | "CheckInterrupted" | "ClearInterrupted";
export type moneytype_t   = "Credit" | "Cup" | "NFC" | "Suica" | "iD" | "QP" | "WAON" | "Edy" | "nanaco" | "All";
export type job_t         = "Sales" | "Refund" | "RefundForce" | "ReservedAuthority" | "RefundReservedAuthority" | "ApprovedSales" | "RefundApprovedSales" | "CardCheck" |
"SubtractValue" | "CancelValue" | "Balance" | "Confirm" | "History" | "PointCharge";
export type journal_t     = "Total" | "Intermediate";
export type detail_t      = "Summary" | "Detail";
export type reprint_t     = "Slip" | "Journal";
export type when_t        = "Last" | "BeforeLast" | "SlipNo";
export type refundtype_t  = "1" | "2";
export type menutype_t    = "Choice";

export type params_t = {
  logid:          string;
  mode:           mode_t;
  menu?:          menus_t;
  moneytype?:     moneytype_t;
  menutype?:      menutype_t;
  job?:           job_t;
  journal?:       journal_t;
  isUseDetail:    boolean;
  detail?:        detail_t;
  reprint?:       reprint_t;
  isUseWhen:      boolean;
  when?:          when_t;
  isUseTraining:  boolean;
  bTraining:      boolean;
  isUsePrinting:  boolean;
  bPrinting:      boolean;
  isUseSelfMode:  boolean;
  bSelfMode:      boolean;
  isUseLump:  boolean;       
  bLump:      boolean;
  isUseWithCash:  boolean;
  bWithCash:      boolean;
  isUsePosExtendData: boolean;
  posExtendData:      string;
  amount:         string;
  taxOther:       string;
  productCode:    string;
  slipNo:         string;
  otherTermJudgeNo: string;
  isUseManualFlg: boolean;
  manualFlg:      boolean;
  pan:            string;
  isUseApprovalNumber:  boolean;
  approvalNumber:       string;
  isUseSlipNo: boolean;
  isUseCancelAmount: boolean;
  isUseTaxOtherAmount: boolean;
  isUseProductCode: boolean;
  isUseCancelType:  boolean;
  cancelType?:      refundtype_t;
  isUseCancelPaymentDiv: boolean;
  cancelPaymentDiv: string;
  isUseInstallmentsNumber: boolean;
  installmentsNumber: string;
  isUseCancelEdit:  boolean;
  cancelEdit:       boolean;
  returnUrl:      string;
};

export type keyvalue_t = {[_: string]: string};
